[package]
name = "ruxy"
version = "0.1.0"
authors = ["Jake Swanson <jakswa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
reqwest = "0.11"